version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: damo-server
    depends_on:
      - redis
      - database
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}
    environment:
      - STORAGE_PATH=${STORAGE_PATH}
    volumes:
      - damo-storage:${STORAGE_PATH}
    restart: always

  database:
    image: postgres:latest
    container_name: damo-database
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: -p ${DB_PORT}
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: always
    volumes:
      - damo-database:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: damo-redis
    command: --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD}
    expose:
      - ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - damo-redis:/data
    restart: always

volumes:
  damo-database:
  damo-redis:
  damo-storage: