services:
  postgres:
    image: 'postgres'
    environment:
      - 'POSTGRES_DB=damo_local_db'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'

  redis:
    image: redis:latest
    container_name: damo_redis
    restart: always
    ports:
      - 6379:6379
