server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:50241/damo_local_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret: c3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwQ

  data:
    redis:
      host: localhost
      port: 6379

  verification-code:
    length: 6
    expire-time: 300000

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: tae195611@gmail.com
    password: rfwx gyvl jgsj xguc
    properties:
      smtp.auth: true
      mail:
        smtp:
          starttls:
            enable: true
            required: true
    test-connection: true
